version: '2'

volumes:
  db:
    {}

networks:
  frontend:
    external: true
  backend:
    driver: bridge


services:
  web:
    restart: always
    image: pbc/httpd:alpine
    build:
      context: .
      dockerfile: Dockerfile.httpd
    volumes:
    - ./:/var/www/html
    expose:
    - "80"
    labels:
    - "traefik.frontend.rule=Host:${SERVER_NAME}"
    - "traefik.docker.network=frontend"
    networks:
    - frontend
    - backend

  laravel:
    restart: always
    build: .
    image: pbc/laravel:latest
    environment:
      ServerName: ${SERVER_NAME}
    volumes:
      - ./:/var/www/html/
    expose:
      - "9000"
    networks:
      - backend

  db:
    restart: always
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql/
#      - ./sql_exp_local/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      explicit_defaults_for_timestamp: 1
      TIMESTAMP: NOT NULL
    ports:
      - "3306"
    networks:
      - backend

  redis:
    image: redis:3
    restart: always
    expose:
      - '6379'
    networks:
      - backend
    #TODO: redis conf file for security
